application: djskgen
version: 1
runtime: python36
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "2.0.4"

builtins:
- django_wsgi: on

handlers:
- url: /static
  static_dir: static

env_variables:
  DJANGO_SETTINGS_MODULE: 'core.settings'
